version: '2'

# run the app locally as if it were in production mode

services:
  app:
    build: .
    tty: true
    volumes:
    - static-volume:/code/public/static
    environment:
    - RDS_HOSTNAME=db
    - RDS_PORT=5432
    - RDS_DB_NAME=postgres
    - RDS_USERNAME=postgres
    - RDS_PASSWORD=password
    - EMAIL_HOST=mail
    - EMAIL_PORT=1025
    depends_on:
    - db
    - mail
  db:
    image: postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - ./.postgres:/var/lib/postgresql/data/pgdata
  mail:
    image: mailhog/mailhog
    ports:
    - 8025:8025
  nginx:
    image: accent/rancher-django-proxy:latest
    tty: true
    volumes:
    - static-volume:/www/static
    depends_on:
    - app
    ports:
    - 8000:80

volumes:
  static-volume:
