version: '2'

services:
  app:
    build: .
    env_file:
    - docker.env
    command: ./devserver.sh
    volumes_from:
    - app-datavolume
    depends_on:
    - db
    - mail
    ports:
    - "8000:8000"

  db:
    image: postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes_from:
    - db-datavolume
    ports:
    - "54321:5432"

  mail:
    image: mailhog/mailhog
    expose:
    - "1025"
    ports:
    - "8025:8025"

  app-datavolume:
    image: busybox
    volumes:
    - .:/var/app
    command: /bin/echo

  db-datavolume:
    image: busybox
    volumes:
    - ./.postgres:/var/lib/postgresql/data/pgdata
    command: /bin/echo
