# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import general.blocks.h1
import general.blocks.h2
import general.blocks.h3
import general.blocks.h4
import general.blocks.h5
import general.blocks.hr
import general.blocks.image
import general.blocks.markdown
import modelcluster.fields
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks
import wagtail.wagtailsearch.index
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtaildocs', '0007_merge'),
        ('wagtailcore', '0039_collectionviewrestriction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('template_string', models.CharField(choices=[('general/basic.html', 'Basic Template'), ('general/basic_with_child_menu.html', 'Basic Template with Child Menu'), ('general/basic_with_sibling_menu.html', 'Basic Template with Sibling Menu'), ('general/basic_with_right_child_menu.html', 'Basic Template with Right Child Menu'), ('general/basic_with_right_sibling_menu.html', 'Basic Template with Right Sibling Menu')], max_length=255, verbose_name='Template')),
                ('body', wagtail.wagtailcore.fields.StreamField((('h1', general.blocks.h1.H1Block()), ('h2', general.blocks.h2.H2Block()), ('h3', general.blocks.h3.H3Block()), ('h4', general.blocks.h4.H4Block()), ('h5', general.blocks.h5.H5Block()), ('hr', general.blocks.hr.HrBlock()), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('markdown', general.blocks.markdown.MarkDownBlock(rows=10)), ('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('alignment', general.blocks.image.ImageFormatChoiceBlock())))), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse')), ('pullquote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), ('cite', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock(help_text='Paste your embed URL ie: https://www.youtube.com/watch?v=05GKqTZGRXU', icon='media')), ('custom_content', wagtail.wagtailsnippets.blocks.SnippetChooserBlock('general.CustomContent'))))),
                ('feed_image', models.ForeignKey(blank=True, help_text='An image that can be used to promote this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BasicPageCarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtaildocs.Document')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CustomContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', wagtail.wagtailcore.fields.StreamField((('h1', general.blocks.h1.H1Block()), ('h2', general.blocks.h2.H2Block()), ('h3', general.blocks.h3.H3Block()), ('h4', general.blocks.h4.H4Block()), ('h5', general.blocks.h5.H5Block()), ('hr', general.blocks.hr.HrBlock()), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('markdown', general.blocks.markdown.MarkDownBlock(rows=10)), ('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('alignment', general.blocks.image.ImageFormatChoiceBlock())))), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock(icon='doc-full-inverse')), ('pullquote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), ('cite', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock(help_text='Paste your embed URL ie: https://www.youtube.com/watch?v=05GKqTZGRXU', icon='media'))))),
            ],
            options={
                'ordering': ['title'],
            },
            bases=(wagtail.wagtailsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(blank=True, choices=[('Europe/London', 'Europe/London'), ('UTC', 'UTC')], help_text='Timezone to use globally across the site', max_length=50, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'General',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PagePlaceholder',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('disclaimer', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PageRedirection',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('redirect_to_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='basicpagecarouselitem',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='basicpagecarouselitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='general.BasicPage'),
        ),
    ]
