# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 11:10
from __future__ import unicode_literals

from django.db import migrations


def add_defaults(apps, schema_editor):
    StyleCategory = apps.get_model("general", "StyleCategory")
    Style = apps.get_model("general", "Style")

    db_alias = schema_editor.connection.alias

    bc = StyleCategory.objects.db_manager(db_alias).create(title='BackgroundColour')
    bw = StyleCategory.objects.db_manager(db_alias).create(title='BackgroundWidth')
    bs = StyleCategory.objects.db_manager(db_alias).create(title='ButtonStyle')
    cw = StyleCategory.objects.db_manager(db_alias).create(title='ContainerWidth')
    hp = StyleCategory.objects.db_manager(db_alias).create(title='HorizontalPadding')
    ta = StyleCategory.objects.db_manager(db_alias).create(title='TextAlignment')
    tc = StyleCategory.objects.db_manager(db_alias).create(title='TextColour')
    vp = StyleCategory.objects.db_manager(db_alias).create(title='VerticalPadding')

    Style.objects.using(db_alias).bulk_create([
        Style(title='White', category=bc, css_class='b-white'),
        Style(title='Primary', category=bc, css_class='b-primary'),
        Style(title='Secondary', category=bc, css_class='b-secondary'),
        Style(title='Full Width', category=bw, css_class='full'),
        Style(title='Content Only', category=bw, css_class='content'),
        Style(title='Default', category=bs, css_class='button'),
        Style(title='Primary', category=bs, css_class='button button-primary'),
        Style(title='Secondary', category=bs, css_class='button button-secondary'),
        Style(title='Container', category=cw, css_class='container'),
        Style(title='Fluid Container', category=cw, css_class='container-fluid'),
        Style(title='No Padding', category=hp, css_class='padding-x-none'),
        Style(title='Small', category=hp, css_class='padding-x-sm'),
        Style(title='Medium', category=hp, css_class='padding-x-md'),
        Style(title='Large', category=hp, css_class='padding-x-lg'),
        Style(title='Extra Large', category=hp, css_class='padding-x-xl'),
        Style(title='Left', category=ta, css_class='text-left'),
        Style(title='Centre', category=ta, css_class='text-center'),
        Style(title='Right', category=ta, css_class='text-right'),
        Style(title='Black', category=tc, css_class='c-black'),
        Style(title='White', category=tc, css_class='c-white'),
        Style(title='Primary', category=tc, css_class='c-primary'),
        Style(title='Secondary', category=tc, css_class='c-secondary'),
        Style(title='No Padding', category=vp, css_class='padding-y-none'),
        Style(title='Small', category=vp, css_class='padding-y-sm'),
        Style(title='Medium', category=vp, css_class='padding-y-md'),
        Style(title='Large', category=vp, css_class='padding-y-lg'),
        Style(title='Extra Large', category=vp, css_class='padding-y-xl'),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=add_defaults
        ),
    ]
