# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0039_collectionviewrestriction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentServe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_ip_address', models.CharField(max_length=255, null=True)),
                ('http_user_agent', models.CharField(max_length=255, null=True)),
                ('request_method', models.CharField(max_length=255, null=True)),
                ('query_string', models.CharField(max_length=255, null=True)),
                ('date_accessed', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_accessed'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageServe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_ip_address', models.CharField(max_length=255, null=True)),
                ('http_user_agent', models.CharField(max_length=255, null=True)),
                ('request_method', models.CharField(max_length=255, null=True)),
                ('query_string', models.CharField(max_length=255, null=True)),
                ('date_accessed', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_accessed'],
                'abstract': False,
            },
        ),
    ]
